version: '3'

services:
  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo
    ports:
      - 27017:27017

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379

  elasticsearch:
    extends:
      file: docker-compose.base.yml
      service: elasticsearch
    ports:
      - 9200:9200

  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - 9100:9100

volumes:
  mongo_configdb:
  mongo_db:
  redis_data:
  es_data:
