version: '3'

services:
  app-1:
    extends:
      file: docker-compose.base.yml
      service: app
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3001:3000
    links:
      - mongo:mogo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    volumes:
      - crowi_data_1:/data

  app-2:
    extends:
      file: docker-compose.base.yml
      service: app
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3002:3000
    links:
      - mongo:mogo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    volumes:
      - crowi_data_2:/data

  app-3:
    extends:
      file: docker-compose.base.yml
      service: app
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3003:3000
    links:
      - mongo:mogo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    volumes:
      - crowi_data_3:/data

  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  elasticsearch:
    extends:
      file: docker-compose.base.yml
      service: elasticsearch

volumes:
  crowi_data_!:
  crowi_data_2:
  crowi_data_3:
  mongo_configdb:
  mongo_db:
  redis_data:
  es_data:
